# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 493438aaa63a1f383e9ffd05030942b039072d0ad3b6ff53b647f0ce8b079433b4a51a6230b64d4596f0e44b01d127e7590b68de2513288a655a5e6362854a64

test:
  secret_key_base: fc63cd488e4a863af14c6645ce7ef94af88b7b88bec3febcca5bb15ccfa2e5a584f35f22d85b576b2c96b9b1eb37df29e8fdb03158e534ab205fe91164b9bcd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
